#!/usr/bin/perl

use strict;
use warnings;

use 5.8.0;

use App::Ack ();
use App::Ack::ConfigLoader ();

our $VERSION = '2.00a01';
# Check http://betterthangrep.com/ for updates

# These are all our globals.

MAIN: {
    if ( $App::Ack::VERSION ne $main::VERSION ) {
        App::Ack::die( "Program/library version mismatch\n\t$0 is $main::VERSION\n\t$INC{'App/Ack.pm'} is $App::Ack::VERSION" );
    }

    # Do preliminary arg checking;
    my $env_is_usable = 1;
    for ( @ARGV ) {
        last if ( $_ eq '--' );

        # Get the --thpppt checking out of the way.
        /^--th[pt]+t+$/ && App::Ack::_thpppt($_);

        # See if we want to ignore the environment. (Don't tell Al Gore.)
        if ( /^--(no)?env$/ ) {
            $env_is_usable = defined $1 ? 0 : 1;
        }
    }
    if ( !$env_is_usable ) {
        my @keys = ( 'ACKRC', grep { /^ACK_/ } keys %ENV );
        delete @ENV{@keys};
    }
    App::Ack::load_colors();

    if ( !@ARGV ) {
        App::Ack::show_help();
        exit 1;
    }

    main();
}

sub main {
    my @arg_sources = App::Ack::retrieve_arg_sources();

    my $opt = App::Ack::ConfigLoader::process_args( @arg_sources );

    my $resources;
    if ( $App::Ack::is_filter_mode ) {
        # XXX $resources = App::Ack::resources_iterator_for_standard_input_only();
    }
    else {
        my @start = @ARGV;
        @start = ('.') if not @start;
        $resources = App::Ack::Resources->from_argv( $opt, \@start );
    }
    App::Ack::set_up_pager( $opt->{pager} ) if defined $opt->{pager};

    my $nmatches = 0;
RESOURCES:
    while ( my $resource = $resources->next ) {
        foreach my $filter (@{ $opt->{'filters'} }) {
            next RESOURCES unless $filter->filter($resource);
        }
        if ( $opt->{f} ) {
            print $resource->name, "\n";
            ++$nmatches;
        }
#       elsif ( $opt->{g} ) {
#           if ( App::Ack::resource_name_matches( $resource, $opt ) ) {
#               print $resource->name, "\n";
#               ++$nmatches;
#           }
#       }
#       elsif ( $opt->{l} || $opt->{count} ) {
#           if ( App::Ack::resource_has_match( $resource, $opt ) ) {
#               print $resource->name, "\n";
#               ++$nmatches;
#           }
#       }
#       else {
#           $nmatches += App::Ack::print_matches_in_resource( $resources, $opt );
#       }
    }

    close $App::Ack::fh;
    App::Ack::exit_from_ack( $nmatches );
}
