#!/usr/bin/env perl

use strict;
use warnings;

use Getopt::Long;

my $skip;

GetOptions(
    'skip=i' => \$skip,
);

while (<>) {
    if ( defined $skip && $. % $skip == 0 ) {
        next;
    }
    print;
}
