# This Makefile is for the ack extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.30 (Revision: Revision: 4535 ) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#
#   MakeMaker Parameters:

#     ABSTRACT => q[A grep-like program specifically for large source trees]
#     AUTHOR => q[Andy Lester <andy@petdance.com>]
#     EXE_FILES => [q[ack]]
#     MAN3PODS => {  }
#     NAME => q[ack]
#     PM => { Ack.pm=>q[$(INST_LIBDIR)/App/Ack.pm] }
#     PREREQ_PM => { Test::More=>q[0], Getopt::Long=>q[0], Term::ANSIColor=>q[0] }
#     VERSION_FROM => q[Ack.pm]
#     clean => { FILES=>q[ack-*] }
#     dist => { COMPRESS=>q[gzip -9f], SUFFIX=>q[gz] }

There's not really anything here.  It's just to have something that starts out like a makefile.
